apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sllb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sllb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sllb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "sllb.fullname" . }}
      labels:
        {{- include "sllb.labels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                {{- include "sllb.selectorLabels" . | nindent 16 }}
            topologyKey: "kubernetes.io/hostname"
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.hostNetwork }} 
      hostNetwork: {{ .Values.hostNetwork}}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- range $value := .Values.hostAliases }}
        - ip: {{ $value.ip }}
          hostnames:
          {{- range $hostname := $value.hostnames }}
          - {{ $hostname }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "sllb.fullname" . }}
          command: {{ toYaml .Values.command | nindent 12 }}
          {{- if and .Values.args (not (empty .Values.args)) }}
          args: {{ toYaml .Values.args | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.envs }}
          env:
            {{- range $value := .Values.envs }}
            - name: {{ $value.name }}
              value: {{ $value.value }}
            {{- end}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /app/storage
            - name: timezone
              mountPath: /etc/timezone
              subPath: timezone
            - name: tz-volume
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: logs
          hostPath:
            path: /data/sllb/storage
            type: DirectoryOrCreate
        - name: tz-volume
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone-config-sllb
            items:
            - key: timezone
              path: timezone

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sllb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sllb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type}}
  selector:
    {{- include "sllb.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $value := .Values.service.port }}
    - name: {{ $value.name }}
      protocol: {{ $value.protocol }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
    {{- end }}